Repository thoth-station/thoth-pre-commit-hook, pull requests merged in 2022-06, with the labels that each got.

#2 Initial test for Thoth pre-commit hook
  .pre-commit-hooks.yaml
  OWNERS
  Pipfile
  Pipfile.lock
  README.md
  app.py
  template/__init__.py
  thoth/thoth_pre_commit_hook/__init__.py
  thoth/thoth_pre_commit_hook/thoth-advise
Labels: size/XL

#5 Add username to maintainers
  .thoth.yaml
Labels: size/XS

#16 Fix executable not found error
  .pre-commit-hooks.yaml
  README.md
  setup.py
  thoth-advise
  thoth/thoth_pre_commit_hook/thoth_advise.py
Labels: lgtm, size/M

#21 Add link to recommendation types doc
  README.md
Labels: size/XS

#22 readme: fix example usage
  README.md
Labels: size/XS, approved, needs-ok-to-test

#24 Update OWNERS
  .thoth.yaml
  OWNERS
Labels: size/XS

#23 do not pass file arguments from pre-commit to thanos
  thoth/thoth_pre_commit_hook/thoth_advise.py
Labels: approved, ok-to-test, size/S

#27 run thamos config non interactively
  thoth/thoth_pre_commit_hook/thoth_advise.py
Labels: size/XS, approved, needs-ok-to-test
